version: "3"
services:
  ubuntu16-1:
    build: 
      context: .
      dockerfile: ./targets/ubuntu/Dockerfile
      args:
        - "http_proxy"
        - "https_proxy"
    hostname: ubuntu16-1
    privileged: true
    env_file: .env
  ubuntu16-2:
    build: 
      context: .
      dockerfile: ./targets/ubuntu/Dockerfile
      args:
        - "http_proxy"
        - "https_proxy"
    hostname: ubuntu16-2
    privileged: true
    env_file: .env
  ansible-server:
    build: 
      context: .
      dockerfile: ./ansible/Dockerfile
    volumes:
      - "./ansible/work:/opt/ansible/ansible/work"
    hostname: myansible
    depends_on: 
      - "ubuntu16-1"
      - "ubuntu16-2"
    env_file: .env
